import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';

export default function Home() {

  const images = ["https://images.unsplash.com/photo-1612472844996-40238aff6eab?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80", "https://images.unsplash.com/photo-1626197219310-8be29c1316be?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80", "https://images.unsplash.com/photo-1622658641558-1bf6a846adeb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80", "https://images.unsplash.com/photo-1587052755556-89808205c097?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80", "https://images.unsplash.com/photo-1444837881208-4d46d5c1f127?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2545&q=80", "https://images.unsplash.com/photo-1549041050-386c1c99d655?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2066&q=80", "https://images.unsplash.com/photo-1538370965046-79c0d6907d47?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1738&q=80"];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Image
        className={styles.logo}
        src="/next.svg"
        alt="Next.js Logo"
        width={180}
        height={37}
        priority
      /> */}
      <div className={styles.image_track}>

        <Link href="/valentine">
          <Image
            className={styles.image}
            src={images[0]}
            alt="Cake"
            width={1000}
            height={1000}
            priority
          />
        </Link>

        <Link href="/cake">
          <Image
            className={styles.image}
            src={images[1]}
            alt="Cake"
            width={1000}
            height={1000}
            priority
          />
        </Link>

        <Link href="/bouquet">
          <Image
            className={styles.image}
            src={images[2]}
            alt="Cake"
            width={1000}
            height={1000}
            priority
          />
        </Link>

        <Link href="/letter">
          <Image
            className={styles.image}
            src={images[3]}
            alt="Cake"
            width={1000}
            height={1000}
            priority
          />
        </Link>

        <Link href="/gloomy">
          <Image
            className={styles.image}
            src={images[4]}
            alt="Cake"
            width={1000}
            height={1000}
            priority
          />
        </Link>

        <Link href="/future">
          <Image
            className={styles.image}
            src={images[5]}
            alt="Cake"
            width={1000}
            height={1000}
            priority
          />
        </Link>

        <Link href="/universe">
          <Image
            className={styles.image}
            src={images[6]}
            alt="Cake"
            width={1000}
            height={1000}
            priority
          />
        </Link>

      </div>
    </>
  )
}
